version: '3'

services:

 database:
  container_name: postgres-csc2022
  image: postgres:latest
  ports:
   - "5433:5432"
  volumes:
   - C:\Users\MEMUD ABDULMALIK AYO\data\postgres\csc2022:/data/postgres
  env_file:
   - csc202.env