//console.log("Testing");

//var a;
//a = 10;
//b = 11;
//var c = 12;
//a = "Me";
//console.log(a);

//Arithmetic operations
/*a = 10;
b = 20;
c = a + b;
console.log(c);
console.log(b-a);
console.log(b/a);
console.log(a*b);
console.log(a**2);
a++;
console.log(a);
b--;
console.log(b);
*/

/*String operations
firstname = "Abdulmalik";
lastname = "Memud";
fullname = firstname + " " + lastname;
console.log(fullname);
*/

//Comparison operations
/*a = 10; 
a < 11; //Returns true 
console.log(a < 11); //Displays true in console 
var test = a > 20; //Declares a variable named test and gives it the value of false. 
console.log(test); //Displays false in console 
a >= 10; //Returns true 
a <= 20; //Returns true 
a == 10; //Returns true 
a === "10"; //Returns false because a holds an integer value of 10 and not string value "10"
*/

//Logical operations
/*a = 1; 
b = 2; 
console.log(a < 3 && b < 3); //Prints true as both a and b contain values that are less than 3. 
console.log(a > 3 && b < 3); //Prints false as the first condition (a > 3) is not true. 
console.log(a > 3 || b < 3); //Prints true as at least one condition (b < 3) is true. 
console.log(!(a < 3)); //Prints false as condition (NOT a < 3) is false. 
console.log(!(a < 3) || !(b > 3)); //Prints true as one of the conditions (NOT b > 3) is true. 
*/

//Ternary (conditional) operations
/*var age = 17; 
var adult = (age > 20)? "Yes" : "No"; 
console.log(adult); //This should display the string "No"
*/

//Bitwise operations
/*5 << 1; //Equivalent of 5 * 2 
5 <<2; //Equivalent of 5 * 4 
5 <<3; //Equivalent of 5 * 8 
40 >> 1; //Equivalent of 40 / 2 
40 >>2; //Equivalent of 40 / 4 
40 >>3; //Equivalent of 40 / 8
*/

//The typeof operator
/*typeof  "Pius Onobhayedo";  //Returns the value "string" 
typeof false;  //Returns the value "boolean" 
typeof (10 + 10);  //Returns the value "number" 
typeof 33;  //Returns the value "number"
*/

//The if/else statement
/*var minimumVotingAge = 18; 
var age = 17; 
if (age < minimumVotingAge){ 
console.log("Not eligible to vote"); 
}else{ 
console.log("Eligible to vote"); 
} 
*/

//The switch statement
/*var dayOfTheWeekCount = 1; 
switch (dayOfTheWeekCount){ 
case 1: 
console.log("Sunday"); 
break; 
case 2: 
case 3: 
case 4: 
case 5: 
case 6: 
case 7: 
console.log("Monday"); 
break; 
console.log("Tuesday"); 
break; 
console.log("Wednesday"); 
break; 
console.log("Thursday"); 
break; 
console.log("Friday"); 
break; 
console.log("Saturday"); 
break; 
default: 
console.log("Sorry, day of the week numbered " + dayOfTheWeekCount + " does not exist") 
} //The switch statement prints out Sunday
var ageRange = "below 13"; 
switch (ageRange){ 
case "below 1": 
console.log("Infant"); 
break; 
case "below 13": 
console.log("Pre-teen"); 
break; 
case "below 20": 
console.log("Teenager"); 
break; 
default: 
console.log("Adult") 
}//This switch statement should print out Pre-teen. */

//The for loop
/*for (var c = 1; c < 11; c++){
    if (c==7) continue;
    console.log(c);
}
*/
//The while loop
/*var n = 0; 
while(n != 5){ 
    n = Math.floor((Math.random() * 10)); //math.random will give a floating point number between 0(inclusive) and 1(exclusive)
    console.log(n) //math.floor rounds the number downwards to the nearest whole integer, making the result an integer
}
*/

/*var n = 0; 
while(n != 5){ 
    n = Math.random(); //generate a random number between 0 and 1 exclusive of 1. 
    n = n * 10;//multiply the number generated by 10 
    n = Math.floor(n); //round down 
    console.log(n); //print the final number 
} 
*/

//The do...while loop
/*var x = 0; 
do{ 
    x+= 1; 
    console.log(x) 
}while(x < 10) 
*/

/*var readlineSync = require('readline-sync'); //make the module just installed available for use in our program 
var answer; //declare variable named answer; 
do{ 
    //use question() function to read input and assign the value to answer 
    answer = readlineSync.question('What should I do? [Type "exit" for me to quit]: '); 
    console.log('You asked me to '+ answer) 
}while(answer != 'exit')
*/

/*var readline = require('readline'); //load the readline module into the runtime environment 

//Next, create the input/output interface as required by readline module. 
var readlineAsync = readline.createInterface({ 
    input: process.stdin, 
    output: process.stdout 
}); 

//Next, declare and define a function named recursiveReadLineAsync 
function recursiveReadLineAsync()  { 
    readlineAsync.question('What should I do? [Type "exit" for me to quit]: ', function (answer){ 
        console.log('You asked me to ' + answer) 
        if (answer == 'exit') //Condition for terminating further self call 
            return readlineAsync.close(); //quit the function if answer == exit  
        recursiveReadLineAsync(); //No exit yet. Call self again to ask another question. 
}); 
}; 
//Finally, invoke the defined function to start the recursion 
recursiveReadLineAsync();
*/

//Function declaration
//By direct declaration

/*function addTwoNumbersA(number1, number2){
    return number1 + number2; //Add the two numbers passed when function is called
}

//By expression 
//var addTwoNumbersB = function(number1, number2){
//    return number1 + number2;
//}

console.log(addTwoNumbersA(20,30)); //Call addTwoNumbersA and print return value (50).
console.log(addTwoNumbersB(20,30)); //Call addTwoNumbersB and print return value (50).


console.log(addTwoNumbersA(20,30)); //Call addTwoNumbersA defined below. Correct! 
function addTwoNumbersA(number1, number2){ 
    return number1 + number2; //Add the two numbers passed when function is called 
} 
console.log(addTwoNumbersB(20,30)); //Call addTwoNumbersB defined below. Wrong! 
var addTwoNumbersB = function(number1, number2){ 
    return number1 + number2; //Add the two numbers passed when function is called 
*/

//Passing arguments to function by value or by reference
//Define a function that receives a number to be squared 
/*function square(number){ 
    number = number**2; 
    return number; 
} 
var number = 20; //Declare variable that holds number to be squared 
var numberSquared = square(number); //Pass number (by value) to the square() function  
console.log(numberSquared); //The function returns 400 
console.log(number); //The value of number variable outside the function remains 20
*/

//Capturing arguments as array within the function - the arguments object
/*function multiplier(){
    var product = 1;
    for (var x = 0; x < arguments.length; x++){
        product = product * arguments[x];
    }
    return product;
}
console.log(multiplier(10,30)); //Prints 300 to the console
console.log(multiplier(10,30,10)); //Prints 3000 to the console
*/